#!/bin/bash

if [ "$#" -ne 1 ]
then
  echo "Usage: tpBranchInitialPush branch"
  exit 1
fi

for i in ./* ; do
  if [ -e "$i/.git" ]; then
    directory=$(basename $i)    
    cd $directory
    git push --set-upstream origin $1
    cd ..
  elif [ -d "$i" ]; then
    echo "$i is not a git repo."
  fi
done

echo "$result" | column -t -s "$se"

