#!/bin/bash

for i in ./* ; do
  if [ -e "$i/.git" ]; then
    directory=$(basename $i)
    echo "=================================================================="
    echo $directory
    cd $directory
    git reset --hard
    cd ..
  elif [ -d "$i" ]; then
    echo "$i is not a git repo."
  fi
done

echo "=================================================================="
