#!/bin/bash

if [ "$#" -ne 1 ]
then
  echo "Usage: tpRemoteChange \"<true/false>\""
  exit 1
fi

for i in ./* ; do
  if [ -e "$i/.git" ]; then
    directory=$(basename $i)
    echo "=================================================================="
    echo $directory
    cd $directory
    git config core.bare $1
    cd ..
  elif [ -d "$i" ]; then
    echo "$i is not a git repo."
  fi
done

echo "=================================================================="
