#!/bin/bash

if [ "$#" -ne 2 ]
then
  echo "Usage: tpMergeRemote remote branch"
  exit 1
fi

for i in ./* ; do
  if [ -e "$i/.git" ]; then
    directory=$(basename $i)    
    cd $directory
    echo "=================================================================="
    echo $directory
    git pull $1 $2
    cd ..
  elif [ -d "$i" ]; then
    echo "$i is not a git repo."
  fi
done
echo "=================================================================="
