#!/bin/bash

if [ "$#" -ne 2 ]
then
  echo "Usage: tpRemoteChange \"fromURL\" \"toURL\""
  exit 1
fi

for i in ./* ; do
  if [ -e "$i/.git" ]; then
    directory=$(basename $i)
    echo "=================================================================="
    echo $directory
    cd $directory
    git remote -v
    sed -i -e 's/'$1'\b/'$2'/g' .git/config
    git remote -v
    cd ..
  elif [ -d "$i" ]; then
    echo "$i is not a git repo."
  fi
done

echo "=================================================================="
