#!/bin/bash

result='Module Branch'
nl=$'\n'
for i in ./* ; do
  if [ -e "$i/.git" ]; then
    directory=$(basename $i)    
    cd $directory
    line=`git rev-parse --abbrev-ref HEAD`
    result="$result$nl$directory $line"
    cd ..
  elif [ -d "$i" ]; then
    echo "$i is not a git repo."
  fi
done

echo "$result" | column -t 
