#!/bin/bash

if [ "$#" -ne 1 ]
then
  echo "Usage: tdpBranchCreate branch"
  exit 1
fi

for i in ./* ; do
  if [ -d "$i" ]; then
    directory=$(basename $i)
    echo "=================================================================="
    echo $directory
    cd $directory
    git branch $1
    git checkout $1
    cd ..
  fi
done
echo "=================================================================="
