#!/bin/bash

#---- Update all modules ----
for i in ./* ; do
  if [ -d "$i" ]; then
    
    cd $(basename $i)    
    
    description="documentation/description"
    if [ -e "$description" ]; then    
    remote=$(git config --get remote.origin.url)
    
    scp "$description" "$remote/description"
    fi
    
    cd ..
  fi
done

