#!/bin/bash

#---- Update all projects ----
for i in ./* ; do
  if [ -d "$i" ]; then
    directory=$(basename $i)
    if [[ $directory != build* ]]; then
      echo "=================================================================="
      echo $directory
      cd $directory
      tdpUpdate
      cd ..
    fi
  fi
done
echo "=================================================================="
