#!/bin/bash

if [ "$#" -ne 1 ]
then
  echo "Usage: tdpRemoteDiff \"Remote/Branch\""
  exit 1
fi

for i in ./* ; do
  if [ -d "$i" ]; then
    directory=$(basename $i)
    echo "=================================================================="
    echo $directory
    cd $directory
    git difftool -y -t meld $1 master
    cd ..
  fi
done
echo "=================================================================="
