#!/bin/bash

if [ "$#" -ne 2 ]
then
  echo "Usage: tdpRemoteSetOrigin \"remote\" \"remote-url\""
  exit 1
fi

for i in ./* ; do
  if [ -d "$i" ]; then
    directory=$(basename $i)
    echo "=================================================================="
    echo "git remote set-url origin \"$2$directory.git\""
    cd $directory
    git remote add $1 "$2/$directory.git"
    cd ..
  fi
done
echo "=================================================================="
