#!/bin/bash

if [ "$#" -ne 1 ]
then
  echo "Usage: tdpRemoteSetOrigin \"remote-url\""
  exit 1
fi

for i in ./* ; do
  if [ -d "$i" ]; then
    directory=$(basename $i)
    echo "=================================================================="
    echo "git remote set-url origin \"$1$directory.git\""
    cd $directory
    git remote set-url origin "$1/$directory.git"
    cd ..
  fi
done
echo "=================================================================="
