#!/bin/bash

#---- Update all modules ----
for i in ./* ; do
  if [ -d "$i" ]; then
    directory=$(basename $i)
    cd $directory
    git pull
    cd ..
  fi
done

#---- Check out any modules that we have not yet got ----
for i in ./* ; do
  if [ -d "$i" ]; then

    cd $(basename $i)

    submodules="submodules.pri"
    if [ -e "$submodules" ]; then

      remote=$(git config --get remote.origin.url)
      remote=${remote%/*}
      
      #---- Special case for tdp_build ----
      if [ ! -d "../tdp_build" ]; then
        cd ../
        git "clone" "$remote/tdp_build.git"
        cd $(basename $i)
      fi

      exec<$submodules
      while read line
      do
        if [[ $line == SUBDIRS* ]]; then
        IFS='=' read -a arr <<< "$line"
        for item in "${arr[@]:1}"
        do
          item=$(echo "$item" | tr -d ' ')
          if [ ! -d "../$item" ]; then
            cd ../
            git "clone" "$remote/$item.git"
            cd $(basename $i)
          fi
        done
        fi
      done
    fi

    cd ..
  fi
done
