#!/bin/bash

if [ "$#" -ne 1 ]
then
  echo "Usage: tpBranchCreate branch"
  exit 1
fi

for i in ./* ; do
  if [ -e "$i/.git" ]; then
    directory=$(basename $i)
    echo "=================================================================="
    echo $directory
    cd $directory
    git branch $1
    git checkout $1
    git branch --set-upstream-to=origin/$1 $1
    cd ..
  elif [ -d "$i" ]; then
    echo "$i is not a git repo."
  fi
done
echo "=================================================================="
