#!/bin/bash

if [ "$#" -ne 1 ]
then
  echo "Usage: tpCommit \"Commit message\""
  exit 1
fi

JOBS=$((`nproc`*2))
JOBS=$((JOBS<7 ? JOBS : 7))

if hash parallel 2>/dev/null; then
  TPInternalListDirs | parallel -j $JOBS -I{} TPInternalCommit "\"$1\"" {}
else
  echo "\"parallel\" not found, install with one of the following:"
  echo "  yum install parallel"
  echo "  dnf install parallel"
  echo "  apt-get install parallel"
  echo "  brew install parallel"
  for i in ./* ; do
    if [ -e "$i/.git" ]; then
      directory=$(basename $i)
      echo "=================================================================="
      echo $directory
      cd $directory
      git add -A
      git commit -am "$1"
      git push
      cd ..
    elif [ -d "$i" ]; then
      echo "$i is not a git repo."
    fi
  done
fi

echo "=================================================================="
