#!/bin/bash

if [ "$#" -ne 1 ]
then
  echo "Usage: TPInternalUpdate \"Directory\""
  exit 1
fi

if [ -e "$1/.git" ]; then
  directory=$1
  echo "=================================================================="
  echo $directory
  cd $directory
  git pull
  cd ..
elif [ -d "$1" ]; then
  echo "$1 is not a git repo."
fi

