#!/bin/bash

if [ "$#" -lt 1 ]
then
  echo "Usage: gitBatch <command>"
  exit 1
fi

for i in ./* ; do
  if [ -e "$i/.git" ]; then
    directory=$(basename $i)
    echo "=================================================================="
    echo $directory
    pushd $directory
    $*
    popd
  fi
done
echo "=================================================================="
