#!/bin/bash

if [ "$#" -lt 1 ]
then
  echo "Usage: gitBatchCmdGenIfChanged <command>"
  exit 1
fi

#quoting all params with single quotes and concatenate them in signle line
cmd_line=""
for param in "$@"; do
	cmd_line="$cmd_line '$param'"
done

`dirname ${0}`/gitBatchCmdGenIfChanged "$cmd_line" | parallel -j8 {1}
